# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39062f338c5af55b5aac6525058346bb8ab22e379eae13aa6f6e368ceb699afc925ae566f13444f46e97aefdd2af0e2418c524c8ad199413cd301ad4774e985c

test:
  secret_key_base: 878c2e6e2469b3cffac8bf17c8e1a0a6dbd10e50bc4721f6924ddbcd7a66a668adec3d5eea98323d5962d6f2d7c219b55a7e6a435ac3db1a49522da14b2658d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
